
include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
  errors:
    deprecated_member_use: ignore
    prefer_const_constructors: ignore
    prefer_const_constructors_in_immutables: ignore
    unused_import: ignore
    unused_local_variable: ignore
    use_super_parameters: ignore

linter:
  rules:
