// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA93ZDX3E9-Co0NIrjc_M1vDxnuCfdfwpQ',
    appId: '1:295173464321:web:13d756b4a4fa5ab9aefb00',
    messagingSenderId: '295173464321',
    projectId: 'opensource2004',
    authDomain: 'opensource2004.firebaseapp.com',
    storageBucket: 'opensource2004.firebasestorage.app',
    measurementId: 'G-5B6MCNRBW1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqv8taDJfzVwophhZEHhxEmg22JXwqRNQ',
    appId: '1:772690012297:android:63aa466e1fe809cabc3e58',
    messagingSenderId: '772690012297',
    projectId: 'rhythma',
    storageBucket: 'rhythma.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1_6yvATQi3na38g2Q1rl-eWlvpkcPrUs',
    appId: '1:295173464321:ios:847e09ebd1dcd361aefb00',
    messagingSenderId: '295173464321',
    projectId: 'opensource2004',
    storageBucket: 'opensource2004.firebasestorage.app',
    iosBundleId: 'com.example.rhythma',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1_6yvATQi3na38g2Q1rl-eWlvpkcPrUs',
    appId: '1:295173464321:ios:847e09ebd1dcd361aefb00',
    messagingSenderId: '295173464321',
    projectId: 'opensource2004',
    storageBucket: 'opensource2004.firebasestorage.app',
    iosBundleId: 'com.example.rhythma',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA93ZDX3E9-Co0NIrjc_M1vDxnuCfdfwpQ',
    appId: '1:295173464321:web:5e672788c2685d67aefb00',
    messagingSenderId: '295173464321',
    projectId: 'opensource2004',
    authDomain: 'opensource2004.firebaseapp.com',
    storageBucket: 'opensource2004.firebasestorage.app',
    measurementId: 'G-XCR6EM8HL8',
  );
}
