// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// To regenerate, run `flutterfire configure` and commit the result.
/// NEVER commit raw API keys — use `--dart-define` in CI/CD:
///   flutter run --dart-define=FIREBASE_API_KEY_ANDROID=...
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
        apiKey: const String.fromEnvironment('FIREBASE_API_KEY_WEB',
            defaultValue: ''),
        appId: const String.fromEnvironment('FIREBASE_APP_ID_WEB',
            defaultValue: ''),
        messagingSenderId: const String.fromEnvironment(
            'FIREBASE_MESSAGING_SENDER_ID_WEB',
            defaultValue: ''),
        projectId: const String.fromEnvironment('FIREBASE_PROJECT_ID_WEB',
            defaultValue: ''),
        authDomain: const String.fromEnvironment('FIREBASE_AUTH_DOMAIN_WEB',
            defaultValue: ''),
        storageBucket: const String.fromEnvironment(
            'FIREBASE_STORAGE_BUCKET_WEB',
            defaultValue: ''),
        measurementId: const String.fromEnvironment(
            'FIREBASE_MEASUREMENT_ID_WEB',
            defaultValue: ''),
      );

  static FirebaseOptions get android => FirebaseOptions(
        apiKey: const String.fromEnvironment('FIREBASE_API_KEY_ANDROID',
            defaultValue: ''),
        appId: const String.fromEnvironment('FIREBASE_APP_ID_ANDROID',
            defaultValue: ''),
        messagingSenderId: const String.fromEnvironment(
            'FIREBASE_MESSAGING_SENDER_ID_ANDROID',
            defaultValue: ''),
        projectId: const String.fromEnvironment('FIREBASE_PROJECT_ID_ANDROID',
            defaultValue: ''),
        storageBucket: const String.fromEnvironment(
            'FIREBASE_STORAGE_BUCKET_ANDROID',
            defaultValue: ''),
      );

  static FirebaseOptions get ios => FirebaseOptions(
        apiKey: const String.fromEnvironment('FIREBASE_API_KEY_IOS',
            defaultValue: ''),
        appId: const String.fromEnvironment('FIREBASE_APP_ID_IOS',
            defaultValue: ''),
        messagingSenderId: const String.fromEnvironment(
            'FIREBASE_MESSAGING_SENDER_ID_IOS',
            defaultValue: ''),
        projectId: const String.fromEnvironment('FIREBASE_PROJECT_ID_IOS',
            defaultValue: ''),
        storageBucket: const String.fromEnvironment(
            'FIREBASE_STORAGE_BUCKET_IOS',
            defaultValue: ''),
        iosBundleId: const String.fromEnvironment('FIREBASE_IOS_BUNDLE_ID',
            defaultValue: 'com.example.rhythma'),
      );

  static FirebaseOptions get macos => FirebaseOptions(
        apiKey: const String.fromEnvironment('FIREBASE_API_KEY_MACOS',
            defaultValue: ''),
        appId: const String.fromEnvironment('FIREBASE_APP_ID_MACOS',
            defaultValue: ''),
        messagingSenderId: const String.fromEnvironment(
            'FIREBASE_MESSAGING_SENDER_ID_MACOS',
            defaultValue: ''),
        projectId: const String.fromEnvironment('FIREBASE_PROJECT_ID_MACOS',
            defaultValue: ''),
        storageBucket: const String.fromEnvironment(
            'FIREBASE_STORAGE_BUCKET_MACOS',
            defaultValue: ''),
        iosBundleId: const String.fromEnvironment('FIREBASE_MACOS_BUNDLE_ID',
            defaultValue: 'com.example.rhythma'),
      );

  static FirebaseOptions get windows => FirebaseOptions(
        apiKey: const String.fromEnvironment('FIREBASE_API_KEY_WINDOWS',
            defaultValue: ''),
        appId: const String.fromEnvironment('FIREBASE_APP_ID_WINDOWS',
            defaultValue: ''),
        messagingSenderId: const String.fromEnvironment(
            'FIREBASE_MESSAGING_SENDER_ID_WINDOWS',
            defaultValue: ''),
        projectId: const String.fromEnvironment('FIREBASE_PROJECT_ID_WINDOWS',
            defaultValue: ''),
        authDomain: const String.fromEnvironment('FIREBASE_AUTH_DOMAIN_WINDOWS',
            defaultValue: ''),
        storageBucket: const String.fromEnvironment(
            'FIREBASE_STORAGE_BUCKET_WINDOWS',
            defaultValue: ''),
        measurementId: const String.fromEnvironment(
            'FIREBASE_MEASUREMENT_ID_WINDOWS',
            defaultValue: ''),
      );
}
